# Netlify Configuration for OnlyPump Frontend
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Base directory for the build
  base = "frontend"
  
  # Build command
  command = "npm run build"
  
  # Publish directory - Netlify combines base + publish
  # Since base="frontend", this becomes "frontend/.next"
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Use Netlify's Next.js plugin for optimal deployment
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking
    X-Frame-Options = "DENY"
    
    # XSS protection
    X-XSS-Protection = "1; mode=block"
    
    # Prevent MIME sniffing
    X-Content-Type-Options = "nosniff"
    
    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy (adjust as needed)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.helius-rpc.com https://*.solana.com https://api.helius.xyz wss://*.solana.com;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Production context (main branch)
[context.production]
  command = "npm run build"
  
[context.production.environment]
  NODE_ENV = "production"

# Deploy preview context (pull requests)
[context.deploy-preview]
  command = "npm run build"

# Branch deploy context
[context.branch-deploy]
  command = "npm run build"

# Development context (for testing)
[context.dev]
  command = "npm run build"
